spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-ou80o.pub-cdb.ntruss.com:3306/kboticket?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kboadmin
    password: dbfla1004**

  jpa:
    hibernate:
      ddl-auto: none



# Redis 인스턴스 설정
redis:
  ticketing:
    host: 118.67.132.142
    port: 6379
    password: kboticketredis
    database: 1

  user:
    host: 101.101.210.13
    port: 6380
    password: kboticketredis
    database: 2