spring:
  config:
    import: application-secret.yml

  mail:
    host: smtp.naver.com
    port: 465
    username: ulim9707@naver.com
    password: dbfla970709**
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        auth-code-expiration-millis: 1800000

coolsms:
  apikey: "NCSIXZBREJIIHWBH"
  apisecret: "1LAGEKICZLRWCTGUUXTDOUECQBHKHASJ"
  fromnumber: "01099495201"

payment:
  client-key: test_ck_4yKeq5bgrpXkgK7lG4NxrGX0lzW6
  secret-key: test_sk_QbgMGZzorzzyAGEAgokjrl5E1em4
  base-url: https://api.tosspayments.com/v1/payments/
  confirm-endpoint: /confirm
  cancel-endpoint: /%s/cancel