spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-q1an9.pub-cdb.ntruss.com:3306/kboticket?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kboadmin
    password: dbfla1004**

  jpa:
    hibernate:
      ddl-auto: create

  # Redis 인스턴스 설정
  data:
    redis:
      host: 10.41.182.192
      port: 6379
      password: kboticketredis
      database: 1

  kafka:
    bootstrap-servers: 118.67.132.142:9092



