name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

#    - name: Make application-prod.yml
#      run: |
#        cd ./src/main/resources
#        touch ./application-prod.yml
#        echo "${{ secrets.APPLICATION_PROD_YML }}" > ./application-prod.yml
#      shell: bash

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '7.6'

    - name: Build with Gradle Wrapper
      run: ./gradlew build  --version
